services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  B13\Proxycachemanager\:
    resource: '../Classes/*'
  cache.tx_proxy:
    class: TYPO3\CMS\Core\Cache\Frontend\FrontendInterface
    factory: ['@TYPO3\CMS\Core\Cache\CacheManager', 'getCache']
    arguments: ['tx_proxy']

  B13\Proxycachemanager\Controller\CacheController:
    public: true
    arguments:
      $cache: '@cache.tx_proxy'

  B13\Proxycachemanager\Listener\AfterCacheIsPersisted:
    tags:
      - name: event.listener
        identifier: 'b13-proxycachemanager-afterCacheIsPersisted'
    arguments:
      $cache: '@cache.tx_proxy'
  B13\Proxycachemanager\Hook\FrontendHook:
    public: true
    arguments:
      $cache: '@cache.tx_proxy'

  B13\Proxycachemanager\ResourceStorageOperations\:
    resource: '../Classes/ResourceStorageOperations/*'

  B13\Proxycachemanager\ResourceStorageOperations\Listener\BeforeFileDeleted:
    tags:
      - name: event.listener
        identifier: 'b13-proxycachemanager-beforeFileDeleted'
  B13\Proxycachemanager\ResourceStorageOperations\Listener\BeforeFileMoved:
    tags:
      - name: event.listener
        identifier: 'b13-proxycachemanager-beforeFileMoved'
  B13\Proxycachemanager\ResourceStorageOperations\Listener\BeforeFileRenamed:
    tags:
      - name: event.listener
        identifier: 'b13-proxycachemanager-beforeFileRenamed'
  B13\Proxycachemanager\ResourceStorageOperations\Listener\BeforeFileReplaced:
    tags:
      - name: event.listener
        identifier: 'b13-proxycachemanager-beforeFileReplaced'
  B13\Proxycachemanager\ResourceStorageOperations\Listener\BeforeFolderDeleted:
    tags:
      - name: event.listener
        identifier: 'b13-proxycachemanager-beforeFolderDeleted'
  B13\Proxycachemanager\ResourceStorageOperations\Listener\BeforeFolderMoved:
    tags:
      - name: event.listener
        identifier: 'b13-proxycachemanager-beforeFolderMoved'
  B13\Proxycachemanager\ResourceStorageOperations\Listener\BeforeFolderRenamed:
    tags:
      - name: event.listener
        identifier: 'b13-proxycachemanager-beforeFolderRenamed'
  B13\Proxycachemanager\ResourceStorageOperations\Listener\AfterFileAdded:
    tags:
      - name: event.listener
        identifier: 'b13-proxycachemanager-afterFileAdded'
  B13\Proxycachemanager\Listener\ModifyClearCacheActions:
    tags:
      - name: event.listener
        identifier: 'b13-proxycachemanager-modifyClearCacheActions'
