name: CI

on:
  push:
  pull_request:
  schedule:
    - cron:  '56 5 * * *'

jobs:

  testsuite:
    name: all tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '8.1', '8.2']
        TYPO3: ['11', '12' ]
        include:
          - TYPO3: '13'
            php: '8.3'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up PHP Version
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
      - name: Composer validate
        run: composer validate
      - name: Install composer dependencies TYPO3 13
        if: matrix.TYPO3 == '13'
        run: |
          composer install --no-progress --no-interaction

      - name: Install composer dependencies TYPO3 12
        if: matrix.TYPO3 == '12'
        run: |
          composer require typo3/cms-core:^12.4 --no-progress --no-interaction --dev -W
      - name: Install composer dependencies TYPO3 11
        if: matrix.TYPO3 == '11'
        run: |
          composer require typo3/cms-core:^11.5 --no-progress --no-interaction --dev -W
      - name: Phpstan 11
        if: matrix.TYPO3 == '11'
        run: .Build/bin/phpstan analyze -c Build/phpstan11.neon
      - name: Phpstan 12
        if: matrix.TYPO3 == '12'
        run: .Build/bin/phpstan analyze -c Build/phpstan12.neon
      - name: Phpstan 13
        if: matrix.TYPO3 == '13'
        run: .Build/bin/phpstan analyze -c Build/phpstan13.neon
      - name: Phpcsfix
        run: .Build/bin/php-cs-fixer fix --config=Build/php-cs-fixer.php --dry-run --stop-on-violation --using-cache=no

